Repository t1mmen/srtd, pull requests merged in 2025-01, with the labels that each got.

#14 feat: Polish and improvements
  .changeset/cuddly-elephants-shave.md
  .changeset/quiet-seals-peel.md
  .changeset/sharp-owls-boil.md
  .changeset/tricky-lemons-type.md
  .changeset/wise-fishes-kick.md
  README.md
  package.json
  readme-screenshot.png
  src/__tests__/vitest.setup.ts
  src/commands/_app.tsx
  src/commands/apply.tsx
  src/commands/clear.tsx
  src/commands/index.tsx
  src/commands/watch.tsx
  src/hooks/useTemplateManager.ts
  src/lib/templateManager.test.ts
  src/lib/templateManager.ts
  src/utils/config.ts
  src/utils/databaseConnection.ts
  srtd.config.json
Labels: Review effort [1-5]: 4, feat

#20 feat: Solidification/polish chores
  .changeset/honest-tigers-eat.md
  .changeset/young-pots-float.md
  package-lock.json
  package.json
  src/__tests__/apply.test.tsx
  src/__tests__/build.test.tsx
  src/__tests__/vitest.setup.ts
  src/__tests__/watch.test.tsx
  src/commands/_app.tsx
  src/commands/apply.tsx
  src/commands/build.tsx
  src/commands/clear.tsx
  src/commands/index.tsx
  src/commands/register.tsx
  src/commands/watch.tsx
  src/components/Branding.tsx
  src/components/ProcessingResults.tsx
  src/components/Quittable.tsx
  src/components/StatBadge.tsx
  src/components/TimeSince.tsx
  src/hooks/useDatabaseConnection.ts
  src/hooks/useFullscreen.ts
  src/hooks/useTemplateProcessor.ts
  src/lib/templateManager.test.ts
  src/lib/templateManager.ts
  src/utils/applyMigrations.test.ts
  src/utils/databaseConnection.test.ts
  src/utils/databaseConnection.ts
  src/utils/logger.ts
  src/utils/registerTemplate.ts
  vitest.config.ts
Labels: Review effort [1-5]: 4, feat

#22 feat: Add `promote` command
  .changeset/quiet-birds-play.md
  .gitignore
  README.md
  package-lock.json
  package.json
  readme-demo.gif
  readme-demo.tape
  readme-screenshot.png
  readme-screenshot.tape
  scripts/record_demo.sh
  src/__tests__/promote.test.tsx
  src/commands/apply.tsx
  src/commands/build.tsx
  src/commands/index.tsx
  src/commands/init.tsx
  src/commands/promote.tsx
  src/hooks/useTemplateProcessor.ts
  src/lib/templateManager.test.ts
Labels: feat, Review effort [1-5]: 3

#25 fix: Correct template path resolution
  .changeset/thin-clocks-fail.md
Labels: Review effort [1-5]: 1

#28 fix: changed import assert to with
  .changeset/cool-games-listen.md
  src/cli.tsx
  src/components/Branding.tsx
Labels: Review effort [1-5]: 1
